service: te-sample-${self:custom.stage}
package:
  individually: true

provider:
  name: aws
  region: us-east-1
  stage: dev
  profile: te-hai
  role: LambdaRole
  environment:
    #mysql
    MYSQL_HOST: ${self:custom.MYSQL.HOST}
    MYSQL_PORT: ${self:custom.MYSQL.PORT}
    
    #common
    DB_NAME: ${self:custom.DB_NAME}
    USERNAME: ${self:custom.USERNAME}
    PASSWORD: ${self:custom.PASSWORD}
custom:
  webpack:
    webpackConfig: ../webpack.config.js
  DB_NAME: tadev
  USERNAME: master
  PASSWORD: password
  MYSQL:
    HOST:
      Fn::GetAtt: [MySqlRDSInstance, Endpoint.Address]
    PORT:
      Fn::GetAtt: [MySqlRDSInstance, Endpoint.Port]
plugins:
  - serverless-pseudo-parameters
  - serverless-offline
resources:
  Resources:
    LambdaRole: ${file(./resource/LambdaRole.yml)}
    
functions:
  hello:
    handler: src/handler.hello
      events: 
        - http:
            path: /
            method: get
