DependsOn: ServerlessVPC
Type: AWS::EC2::Subnet
Properties:
  VpcId:
    Ref: ServerlessVPC
  AvailabilityZone: ${self:provider.region}a
  CidrBlock: 10.0.0.0/24
  Tags: 
    - 
      Key: "Name"
      Value: "ServerlessSubnetA"